repos:
  # --------------------------------------------------------------------------------------
  # General
  # --------------------------------------------------------------------------------------
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.2.0"
    hooks:
      - id: check-added-large-files
        name: "General: Check for large added files"
      - id: trailing-whitespace
        name: "General: Trim trailing whitespace"
      - id: end-of-file-fixer
        name: "General: Fix end of files"

  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: "v0.31.1"
    hooks:
      - id: markdownlint
        name: "General: Markdown linter"

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.6.2"
    hooks:
      - id: prettier
        name: "General: Prettier formatter"

  # --------------------------------------------------------------------------------------
  # Security
  # --------------------------------------------------------------------------------------
  - repo: "https://github.com/Yelp/detect-secrets"
    rev: "v1.2.0"
    hooks:
      - id: detect-secrets
        name: "Security: Detect secrets"
